//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrJack.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MrJack.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap AboutLogo {
            get {
                object obj = ResourceManager.GetObject("AboutLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bert {
            get {
                object obj = ResourceManager.GetObject("Bert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BertInnocent {
            get {
                object obj = ResourceManager.GetObject("BertInnocent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Board {
            get {
                object obj = ResourceManager.GetObject("Board", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CardBack {
            get {
                object obj = ResourceManager.GetObject("CardBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CardBert {
            get {
                object obj = ResourceManager.GetObject("CardBert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CardGoodley {
            get {
                object obj = ResourceManager.GetObject("CardGoodley", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CardGull {
            get {
                object obj = ResourceManager.GetObject("CardGull", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CardHelp {
            get {
                object obj = ResourceManager.GetObject("CardHelp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CardHolmes {
            get {
                object obj = ResourceManager.GetObject("CardHolmes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CardLestrade {
            get {
                object obj = ResourceManager.GetObject("CardLestrade", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CardNoWitness {
            get {
                object obj = ResourceManager.GetObject("CardNoWitness", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CardSelectInspector {
            get {
                object obj = ResourceManager.GetObject("CardSelectInspector", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CardSelectJack {
            get {
                object obj = ResourceManager.GetObject("CardSelectJack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CardSelectWintess {
            get {
                object obj = ResourceManager.GetObject("CardSelectWintess", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CardSmith {
            get {
                object obj = ResourceManager.GetObject("CardSmith", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CardStealthy {
            get {
                object obj = ResourceManager.GetObject("CardStealthy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CardWatson {
            get {
                object obj = ResourceManager.GetObject("CardWatson", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CardWitness {
            get {
                object obj = ResourceManager.GetObject("CardWitness", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClockShape {
            get {
                object obj = ResourceManager.GetObject("ClockShape", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Coordinates {
            get {
                object obj = ResourceManager.GetObject("Coordinates", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cordon {
            get {
                object obj = ResourceManager.GetObject("Cordon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CordonPath {
            get {
                object obj = ResourceManager.GetObject("CordonPath", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cover {
            get {
                object obj = ResourceManager.GetObject("Cover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Escape {
            get {
                object obj = ResourceManager.GetObject("Escape", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Goodley {
            get {
                object obj = ResourceManager.GetObject("Goodley", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GoodleyInnocent {
            get {
                object obj = ResourceManager.GetObject("GoodleyInnocent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gull {
            get {
                object obj = ResourceManager.GetObject("Gull", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GullInnocent {
            get {
                object obj = ResourceManager.GetObject("GullInnocent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HexFrom {
            get {
                object obj = ResourceManager.GetObject("HexFrom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HexTo {
            get {
                object obj = ResourceManager.GetObject("HexTo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HexVia {
            get {
                object obj = ResourceManager.GetObject("HexVia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Holmes {
            get {
                object obj = ResourceManager.GetObject("Holmes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HolmesInnocent {
            get {
                object obj = ResourceManager.GetObject("HolmesInnocent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JackBert {
            get {
                object obj = ResourceManager.GetObject("JackBert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JackGoodley {
            get {
                object obj = ResourceManager.GetObject("JackGoodley", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JackGull {
            get {
                object obj = ResourceManager.GetObject("JackGull", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JackHolmes {
            get {
                object obj = ResourceManager.GetObject("JackHolmes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JackLestrade {
            get {
                object obj = ResourceManager.GetObject("JackLestrade", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JackSmith {
            get {
                object obj = ResourceManager.GetObject("JackSmith", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JackStealthy {
            get {
                object obj = ResourceManager.GetObject("JackStealthy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JackWatson {
            get {
                object obj = ResourceManager.GetObject("JackWatson", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Lestrade {
            get {
                object obj = ResourceManager.GetObject("Lestrade", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LestradeInnocent {
            get {
                object obj = ResourceManager.GetObject("LestradeInnocent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Light1 {
            get {
                object obj = ResourceManager.GetObject("Light1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Light2 {
            get {
                object obj = ResourceManager.GetObject("Light2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Light3 {
            get {
                object obj = ResourceManager.GetObject("Light3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Light4 {
            get {
                object obj = ResourceManager.GetObject("Light4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LightAlways {
            get {
                object obj = ResourceManager.GetObject("LightAlways", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap None {
            get {
                object obj = ResourceManager.GetObject("None", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Round1 {
            get {
                object obj = ResourceManager.GetObject("Round1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Round2 {
            get {
                object obj = ResourceManager.GetObject("Round2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Round3 {
            get {
                object obj = ResourceManager.GetObject("Round3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Round4 {
            get {
                object obj = ResourceManager.GetObject("Round4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Round5 {
            get {
                object obj = ResourceManager.GetObject("Round5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Round6 {
            get {
                object obj = ResourceManager.GetObject("Round6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Round7 {
            get {
                object obj = ResourceManager.GetObject("Round7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Round8 {
            get {
                object obj = ResourceManager.GetObject("Round8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Smith {
            get {
                object obj = ResourceManager.GetObject("Smith", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmithInnocent {
            get {
                object obj = ResourceManager.GetObject("SmithInnocent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] SndNewGame {
            get {
                object obj = ResourceManager.GetObject("SndNewGame", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SndTurn {
            get {
                object obj = ResourceManager.GetObject("SndTurn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Stealthy {
            get {
                object obj = ResourceManager.GetObject("Stealthy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StealthyInnocent {
            get {
                object obj = ResourceManager.GetObject("StealthyInnocent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sub1 {
            get {
                object obj = ResourceManager.GetObject("Sub1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sub2 {
            get {
                object obj = ResourceManager.GetObject("Sub2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sub3 {
            get {
                object obj = ResourceManager.GetObject("Sub3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sub4 {
            get {
                object obj = ResourceManager.GetObject("Sub4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap t10 {
            get {
                object obj = ResourceManager.GetObject("t10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap t7 {
            get {
                object obj = ResourceManager.GetObject("t7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap t8 {
            get {
                object obj = ResourceManager.GetObject("t8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap t9 {
            get {
                object obj = ResourceManager.GetObject("t9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TabMoves {
            get {
                object obj = ResourceManager.GetObject("TabMoves", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TabNotes {
            get {
                object obj = ResourceManager.GetObject("TabNotes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Watson1 {
            get {
                object obj = ResourceManager.GetObject("Watson1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Watson2 {
            get {
                object obj = ResourceManager.GetObject("Watson2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Watson3 {
            get {
                object obj = ResourceManager.GetObject("Watson3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Watson4 {
            get {
                object obj = ResourceManager.GetObject("Watson4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Watson5 {
            get {
                object obj = ResourceManager.GetObject("Watson5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Watson6 {
            get {
                object obj = ResourceManager.GetObject("Watson6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WatsonInnocent1 {
            get {
                object obj = ResourceManager.GetObject("WatsonInnocent1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WatsonInnocent2 {
            get {
                object obj = ResourceManager.GetObject("WatsonInnocent2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WatsonInnocent3 {
            get {
                object obj = ResourceManager.GetObject("WatsonInnocent3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WatsonInnocent4 {
            get {
                object obj = ResourceManager.GetObject("WatsonInnocent4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WatsonInnocent5 {
            get {
                object obj = ResourceManager.GetObject("WatsonInnocent5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WatsonInnocent6 {
            get {
                object obj = ResourceManager.GetObject("WatsonInnocent6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
